server:
  port: 8063
spring:
  data:
    redis:
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      sentinel:
        master: mymaster
        nodes:
          - 127.0.0.1:6379
      lettuce:
        shutdown-timeout: 200ms